
const employeeData = [
  {
    id: 1,
    name: 'Alexandra Thompson',
    position: 'Senior Software Engineer',
    department: 'Engineering',
    rating: 4.8,
    skills: ['JavaScript', 'React', 'Node.js', 'TypeScript'],
    projects: ['E-commerce Platform', 'Internal Tools'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/women/1.jpg',
    email: 'alexandra.thompson@example.com',
    phone: '(555) 123-4567',
    joinDate: '2018-06-15'
  },
  {
    id: 2,
    name: 'Michael Johnson',
    position: 'Product Manager',
    department: 'Product',
    rating: 4.5,
    skills: ['Product Strategy', 'Agile', 'User Stories', 'Roadmapping'],
    projects: ['Mobile App Launch', 'Feature Prioritization'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/men/2.jpg',
    email: 'michael.johnson@example.com',
    phone: '(555) 234-5678',
    joinDate: '2019-03-22'
  },
  {
    id: 3,
    name: 'Emily Davis',
    position: 'UX Designer',
    department: 'Design',
    rating: 4.6,
    skills: ['Figma', 'UI/UX Design', 'User Research', 'Prototyping'],
    projects: ['Website Redesign', 'Mobile App UI'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/women/3.jpg',
    email: 'emily.davis@example.com',
    phone: '(555) 345-6789',
    joinDate: '2020-01-10'
  },
  {
    id: 4,
    name: 'David Wilson',
    position: 'Backend Developer',
    department: 'Engineering',
    rating: 4.4,
    skills: ['Java', 'Spring Boot', 'Microservices', 'AWS'],
    projects: ['API Gateway', 'Authentication Service'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/men/4.jpg',
    email: 'david.wilson@example.com',
    phone: '(555) 456-7890',
    joinDate: '2019-08-15'
  },
  {
    id: 5,
    name: 'Sarah Martinez',
    position: 'Marketing Specialist',
    department: 'Marketing',
    rating: 4.2,
    skills: ['Content Marketing', 'SEO', 'Social Media', 'Analytics'],
    projects: ['Brand Awareness Campaign', 'Lead Generation'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/women/5.jpg',
    email: 'sarah.martinez@example.com',
    phone: '(555) 567-8901',
    joinDate: '2020-03-05'
  },
  {
    id: 6,
    name: 'James Taylor',
    position: 'DevOps Engineer',
    department: 'Operations',
    rating: 4.7,
    skills: ['Docker', 'Kubernetes', 'CI/CD', 'Terraform'],
    projects: ['Infrastructure Automation', 'Deployment Pipeline'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/men/6.jpg',
    email: 'james.taylor@example.com',
    phone: '(555) 678-9012',
    joinDate: '2018-11-20'
  },
  {
    id: 7,
    name: 'Jennifer Anderson',
    position: 'Data Scientist',
    department: 'Analytics',
    rating: 4.9,
    skills: ['Python', 'Machine Learning', 'Data Visualization', 'SQL'],
    projects: ['Customer Segmentation', 'Predictive Analytics'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/women/7.jpg',
    email: 'jennifer.anderson@example.com',
    phone: '(555) 789-0123',
    joinDate: '2019-05-12'
  },
  {
    id: 8,
    name: 'Robert Thomas',
    position: 'Frontend Developer',
    department: 'Engineering',
    rating: 4.3,
    skills: ['JavaScript', 'React', 'CSS', 'HTML'],
    projects: ['UI Components Library', 'Dashboard Redesign'],
    status: 'On Leave',
    image: 'https://randomuser.me/api/portraits/men/8.jpg',
    email: 'robert.thomas@example.com',
    phone: '(555) 890-1234',
    joinDate: '2020-07-18'
  },
  {
    id: 9,
    name: 'Jessica Jackson',
    position: 'HR Manager',
    department: 'Human Resources',
    rating: 4.5,
    skills: ['Recruitment', 'Employee Relations', 'Performance Management', 'Training'],
    projects: ['Onboarding Process Improvement', 'Employee Engagement'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/women/9.jpg',
    email: 'jessica.jackson@example.com',
    phone: '(555) 901-2345',
    joinDate: '2017-09-30'
  },
  {
    id: 10,
    name: 'Christopher White',
    position: 'QA Engineer',
    department: 'Engineering',
    rating: 4.4,
    skills: ['Test Automation', 'Selenium', 'API Testing', 'Test Planning'],
    projects: ['Automated Test Framework', 'Regression Testing'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/men/10.jpg',
    email: 'christopher.white@example.com',
    phone: '(555) 012-3456',
    joinDate: '2019-11-05'
  },
  {
    id: 11,
    name: 'Amanda Harris',
    position: 'Content Strategist',
    department: 'Marketing',
    rating: 4.6,
    skills: ['Content Creation', 'SEO', 'Copywriting', 'Editorial Planning'],
    projects: ['Blog Relaunch', 'Content Calendar'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/women/11.jpg',
    email: 'amanda.harris@example.com',
    phone: '(555) 123-4567',
    joinDate: '2020-02-15'
  },
  {
    id: 12,
    name: 'Daniel Clark',
    position: 'Systems Administrator',
    department: 'IT',
    rating: 4.3,
    skills: ['Linux', 'Windows Server', 'Networking', 'Security'],
    projects: ['Server Migration', 'Security Audit'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/men/12.jpg',
    email: 'daniel.clark@example.com',
    phone: '(555) 234-5678',
    joinDate: '2018-08-10'
  },
  {
    id: 13,
    name: 'Melissa Lewis',
    position: 'Financial Analyst',
    department: 'Finance',
    rating: 4.7,
    skills: ['Financial Modeling', 'Budgeting', 'Forecasting', 'Excel'],
    projects: ['Annual Budget', 'Cost Reduction Initiative'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/women/13.jpg',
    email: 'melissa.lewis@example.com',
    phone: '(555) 345-6789',
    joinDate: '2019-01-20'
  },
  {
    id: 14,
    name: 'Matthew Walker',
    position: 'Mobile Developer',
    department: 'Engineering',
    rating: 4.5,
    skills: ['Swift', 'Kotlin', 'React Native', 'Mobile UI'],
    projects: ['iOS App', 'Android App'],
    status: 'Remote',
    image: 'https://randomuser.me/api/portraits/men/14.jpg',
    email: 'matthew.walker@example.com',
    phone: '(555) 456-7890',
    joinDate: '2020-05-05'
  },
  {
    id: 15,
    name: 'Elizabeth Hall',
    position: 'Customer Success Manager',
    department: 'Customer Support',
    rating: 4.8,
    skills: ['Customer Relationship', 'Problem Solving', 'Product Knowledge', 'Communication'],
    projects: ['Customer Retention Program', 'Satisfaction Survey'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/women/15.jpg',
    email: 'elizabeth.hall@example.com',
    phone: '(555) 567-8901',
    joinDate: '2018-12-10'
  },
  {
    id: 16,
    name: 'Andrew Young',
    position: 'Security Engineer',
    department: 'IT',
    rating: 4.6,
    skills: ['Penetration Testing', 'Security Audits', 'Vulnerability Assessment', 'Encryption'],
    projects: ['Security Framework Implementation', 'Compliance Audit'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/men/16.jpg',
    email: 'andrew.young@example.com',
    phone: '(555) 678-9012',
    joinDate: '2019-07-15'
  },
  {
    id: 17,
    name: 'Nicole Allen',
    position: 'Graphic Designer',
    department: 'Design',
    rating: 4.4,
    skills: ['Adobe Creative Suite', 'Typography', 'Branding', 'Illustration'],
    projects: ['Brand Refresh', 'Marketing Materials'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/women/17.jpg',
    email: 'nicole.allen@example.com',
    phone: '(555) 789-0123',
    joinDate: '2020-03-20'
  },
  {
    id: 18,
    name: 'Kevin Scott',
    position: 'Database Administrator',
    department: 'Engineering',
    rating: 4.5,
    skills: ['SQL', 'Database Design', 'Performance Tuning', 'Data Migration'],
    projects: ['Database Optimization', 'Backup Strategy'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/men/18.jpg',
    email: 'kevin.scott@example.com',
    phone: '(555) 890-1234',
    joinDate: '2018-10-05'
  },
  {
    id: 19,
    name: 'Stephanie Green',
    position: 'Project Coordinator',
    department: 'Project Management',
    rating: 4.2,
    skills: ['Project Planning', 'Documentation', 'Stakeholder Management', 'Reporting'],
    projects: ['Product Launch', 'Process Improvement'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/women/19.jpg',
    email: 'stephanie.green@example.com',
    phone: '(555) 901-2345',
    joinDate: '2019-09-15'
  },
  {
    id: 20,
    name: 'Brian Adams',
    position: 'Sales Representative',
    department: 'Sales',
    rating: 4.7,
    skills: ['Negotiation', 'CRM', 'Relationship Building', 'Presentation'],
    projects: ['New Market Expansion', 'Key Account Management'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/men/20.jpg',
    email: 'brian.adams@example.com',
    phone: '(555) 012-3456',
    joinDate: '2018-05-10'
  },
  {
    id: 21,
    name: 'Rebecca Baker',
    position: 'Content Writer',
    department: 'Marketing',
    rating: 4.3,
    skills: ['Copywriting', 'SEO', 'Research', 'Editing'],
    projects: ['Website Content', 'Email Campaigns'],
    status: 'Remote',
    image: 'https://randomuser.me/api/portraits/women/21.jpg',
    email: 'rebecca.baker@example.com',
    phone: '(555) 123-4567',
    joinDate: '2020-01-15'
  },
  {
    id: 22,
    name: 'Joshua Nelson',
    position: 'Network Engineer',
    department: 'IT',
    rating: 4.5,
    skills: ['Network Design', 'Routing', 'Switching', 'Troubleshooting'],
    projects: ['Network Upgrade', 'WAN Optimization'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/men/22.jpg',
    email: 'joshua.nelson@example.com',
    phone: '(555) 234-5678',
    joinDate: '2019-03-10'
  },
  {
    id: 23,
    name: 'Laura Carter',
    position: 'Business Analyst',
    department: 'Business Development',
    rating: 4.6,
    skills: ['Requirements Gathering', 'Process Mapping', 'Data Analysis', 'Documentation'],
    projects: ['System Requirements', 'Process Improvement'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/women/23.jpg',
    email: 'laura.carter@example.com',
    phone: '(555) 345-6789',
    joinDate: '2018-11-20'
  },
  {
    id: 24,
    name: 'Brandon Mitchell',
    position: 'Full Stack Developer',
    department: 'Engineering',
    rating: 4.8,
    skills: ['JavaScript', 'React', 'Node.js', 'MongoDB'],
    projects: ['Customer Portal', 'Internal Dashboard'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/men/24.jpg',
    email: 'brandon.mitchell@example.com',
    phone: '(555) 456-7890',
    joinDate: '2019-06-15'
  },
  {
    id: 25,
    name: 'Kimberly Perez',
    position: 'UI Designer',
    department: 'Design',
    rating: 4.4,
    skills: ['UI Design', 'Wireframing', 'Prototyping', 'Visual Design'],
    projects: ['Mobile App Redesign', 'Design System'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/women/25.jpg',
    email: 'kimberly.perez@example.com',
    phone: '(555) 567-8901',
    joinDate: '2020-02-10'
  },
  {
    id: 26,
    name: 'Jonathan Roberts',
    position: 'IT Support Specialist',
    department: 'IT',
    rating: 4.2,
    skills: ['Troubleshooting', 'Hardware', 'Software', 'Customer Service'],
    projects: ['Help Desk Improvement', 'IT Documentation'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/men/26.jpg',
    email: 'jonathan.roberts@example.com',
    phone: '(555) 678-9012',
    joinDate: '2019-08-05'
  },
  {
    id: 27,
    name: 'Michelle Turner',
    position: 'Account Manager',
    department: 'Sales',
    rating: 4.7,
    skills: ['Client Relationship', 'Negotiation', 'Sales Strategy', 'Presentation'],
    projects: ['Client Retention', 'Upselling Campaign'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/women/27.jpg',
    email: 'michelle.turner@example.com',
    phone: '(555) 789-0123',
    joinDate: '2018-07-15'
  },
  {
    id: 28,
    name: 'Timothy Phillips',
    position: 'Quality Assurance Analyst',
    department: 'Engineering',
    rating: 4.3,
    skills: ['Manual Testing', 'Test Planning', 'Bug Tracking', 'User Acceptance Testing'],
    projects: ['Product Testing', 'Quality Documentation'],
    status: 'On Leave',
    image: 'https://randomuser.me/api/portraits/men/28.jpg',
    email: 'timothy.phillips@example.com',
    phone: '(555) 890-1234',
    joinDate: '2019-10-10'
  },
  {
    id: 29,
    name: 'Samantha Campbell',
    position: 'Social Media Manager',
    department: 'Marketing',
    rating: 4.5,
    skills: ['Social Media Strategy', 'Content Creation', 'Community Management', 'Analytics'],
    projects: ['Social Media Campaign', 'Influencer Program'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/women/29.jpg',
    email: 'samantha.campbell@example.com',
    phone: '(555) 901-2345',
    joinDate: '2020-04-15'
  },
  {
    id: 30,
    name: 'Eric Parker',
    position: 'Software Architect',
    department: 'Engineering',
    rating: 4.9,
    skills: ['System Design', 'Architecture Patterns', 'Technical Leadership', 'Mentoring'],
    projects: ['System Architecture', 'Technical Roadmap'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/men/30.jpg',
    email: 'eric.parker@example.com',
    phone: '(555) 012-3456',
    joinDate: '2017-12-05'
  },
  {
    id: 31,
    name: 'Rachel Evans',
    position: 'Customer Support Specialist',
    department: 'Customer Support',
    rating: 4.4,
    skills: ['Problem Solving', 'Communication', 'Product Knowledge', 'Empathy'],
    projects: ['Support Documentation', 'Customer Satisfaction'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/women/31.jpg',
    email: 'rachel.evans@example.com',
    phone: '(555) 123-4567',
    joinDate: '2019-05-20'
  },
  {
    id: 32,
    name: 'Justin Edwards',
    position: 'Operations Manager',
    department: 'Operations',
    rating: 4.6,
    skills: ['Process Improvement', 'Team Management', 'Strategic Planning', 'Budgeting'],
    projects: ['Operational Efficiency', 'Team Restructuring'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/men/32.jpg',
    email: 'justin.edwards@example.com',
    phone: '(555) 234-5678',
    joinDate: '2018-03-15'
  },
  {
    id: 33,
    name: 'Olivia Cooper',
    position: 'Product Designer',
    department: 'Design',
    rating: 4.7,
    skills: ['Product Design', 'User Experience', 'Interaction Design', 'Design Thinking'],
    projects: ['Product Redesign', 'User Testing'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/women/33.jpg',
    email: 'olivia.cooper@example.com',
    phone: '(555) 345-6789',
    joinDate: '2019-02-10'
  },
  {
    id: 34,
    name: 'Ryan Murphy',
    position: 'Technical Lead',
    department: 'Engineering',
    rating: 4.8,
    skills: ['Team Leadership', 'Code Review', 'Architecture', 'Mentoring'],
    projects: ['Platform Migration', 'Performance Optimization'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/men/34.jpg',
    email: 'ryan.murphy@example.com',
    phone: '(555) 456-7890',
    joinDate: '2018-09-20'
  },
  {
    id: 35,
    name: 'Lauren Reed',
    position: 'Marketing Manager',
    department: 'Marketing',
    rating: 4.6,
    skills: ['Marketing Strategy', 'Campaign Management', 'Team Leadership', 'Budget Planning'],
    projects: ['Rebranding', 'Market Expansion'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/women/35.jpg',
    email: 'lauren.reed@example.com',
    phone: '(555) 567-8901',
    joinDate: '2018-04-10'
  },
  {
    id: 36,
    name: 'Adam Bailey',
    position: 'Data Engineer',
    department: 'Analytics',
    rating: 4.5,
    skills: ['ETL', 'Data Warehousing', 'SQL', 'Python'],
    projects: ['Data Pipeline', 'Analytics Platform'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/men/36.jpg',
    email: 'adam.bailey@example.com',
    phone: '(555) 678-9012',
    joinDate: '2019-07-05'
  },
  {
    id: 37,
    name: 'Victoria Gray',
    position: 'UX Researcher',
    department: 'Design',
    rating: 4.4,
    skills: ['User Research', 'Usability Testing', 'Interviews', 'Data Analysis'],
    projects: ['User Needs Assessment', 'Usability Study'],
    status: 'Remote',
    image: 'https://randomuser.me/api/portraits/women/37.jpg',
    email: 'victoria.gray@example.com',
    phone: '(555) 789-0123',
    joinDate: '2020-03-15'
  },
  {
    id: 38,
    name: 'Nathan Cook',
    position: 'Cloud Engineer',
    department: 'Operations',
    rating: 4.6,
    skills: ['Cloud Infrastructure', 'AWS', 'Terraform', 'Monitoring'],
    projects: ['Cloud Migration', 'Infrastructure as Code'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/men/38.jpg',
    email: 'nathan.cook@example.com',
    phone: '(555) 890-1234',
    joinDate: '2018-06-20'
  },
  {
    id: 39,
    name: 'Amy Morgan',
    position: 'Recruitment Specialist',
    department: 'Human Resources',
    rating: 4.5,
    skills: ['Talent Acquisition', 'Interviewing', 'Candidate Assessment', 'Onboarding'],
    projects: ['Hiring Process Improvement', 'Talent Pipeline'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/women/39.jpg',
    email: 'amy.morgan@example.com',
    phone: '(555) 901-2345',
    joinDate: '2019-04-05'
  },
  {
    id: 40,
    name: 'Zoe Nelson',
    position: 'Data Analyst',
    department: 'Analytics',
    rating: 4.3,
    skills: ['SQL', 'Tableau', 'Python', 'Data Visualization'],
    projects: ['Sales Forecasting', 'Customer Segmentation'],
    status: 'Active',
    image: 'https://randomuser.me/api/portraits/women/40.jpg',
    email: 'zoe.nelson@example.com',
    phone: '(555) 987-6543',
    joinDate: '2021-11-05'
  }
];

export default employeeData;